### ISSUE TITLE
KDB+ have a Julia library

### ISSUE THREAD

**Issue by femtotrader** [TSDBBench/Ultimate-TSDB-Comparison#12]
https://github.com/enlnt/Q.jl

from @enlnt (@abalkin and @sashkab )

maybe you should add it to https://tsdbbench.github.io/Ultimate-TSDB-Comparison/

**Comment by koppor** [comment]
As usual for OSS devs, I am very short of time. Could you please open a PR against https://github.com/TSDBBench/Ultimate-TSDB-Comparison/blob/master/data/KDBplus.md?

[#hacktoberfest](https://hacktoberfest.digitalocean.com/)

**Comment by abalkin** [comment]
Note that Q.jl have not been updated for Julia 0.7 or 1.0 yet and I have stopped its development last year waiting for the DataFrame and  NamedTuple interfaces to stabilize in Julia.  It is probably time to get back to it.
